export const CHANGE_TRANSCRIPTION_TYPE = 'CHANGE_TRANSCRIPTION_TYPE';
export const CHANGE_CURRENT_FOLIO = 'CHANGE_CURRENT_FOLIO';
export const UPDATE_FOLIO_INDEX = 'UPDATE_FOLIO_INDEX';
export const UPDATE_FOLIO_NAME_INDEX = 'UPDATE_FOLIO_NAME_INDEX';
export const SET_DRAWER_MODE = 'SET_DRAWER_MODE';
