export const CHANGE_TRANSCRIPTION_TYPE = 'CHANGE_TRANSCRIPTION_TYPE';
export const CHANGE_CURRENT_FOLIO = 'CHANGE_CURRENT_FOLIO';
export const UPDATE_FOLIO_INDEX = 'UPDATE_FOLIO_INDEX';
export const UPDATE_FOLIO_NAME_INDEX = 'UPDATE_FOLIO_NAME_INDEX';
export const SET_DRAWER_MODE = 'SET_DRAWER_MODE';

export const SET_LINKED_MODE = 'SET_LINKED_MODE';
export const SET_PANE_SIZES = 'SET_PANE_SIZES';
export const SET_LEFT_PANE_VIEWTYPE = 'SET_LEFT_PANE_VIEWTYPE';
export const SET_RIGHT_PANE_VIEWTYPE = 'SET_RIGHT_PANE_VIEWTYPE';
